# -*- coding: utf-8 -*-
"""generacionBrusselator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dysJi9rryNFIWBzIaR-U9io1xeTjqbJ3
"""

import numpy as np

# -------------------------------
# Parámetros del modelo
# -------------------------------
a = 1.5
b = 2.3
dX = 3
dY = 25

L = 50          # Tamaño del dominio
N = 50         # Número de puntos en x
dx = L / N
dy = dx
dt = 0.01       # Paso temporal
T = 30           # Tiempo total
steps = round(T / dt)

# -------------------------------
# Condiciones iniciales
# -------------------------------
x = np.zeros((N+2, N+2))
y = np.zeros((N+2, N+2))

# Leer condición inicial desde archivo
# cond_x = np.loadtxt("condicion_x.txt", delimiter=",")
# cond_y = np.loadtxt("condicion_y.txt", delimiter=",")

#x[1:N+1, 1:N+1] = cond_x
#y[1:N+1, 1:N+1] = cond_y

# Ejemplo: condición aleatoria
#x[1:N+1, 1:N+1] = np.random.rand(N, N)
#y[1:N+1, 1:N+1] = np.random.rand(N, N)

# Ejemplo: condición equilibrio con pequeña perturbacion
x[1:N+1, 1:N+1] = a*np.ones((N,N))+0.01#*np.random.rand(N,N)
y[1:N+1, 1:N+1] = (b/a)*np.ones((N,N))+0.01#*np.random.rand(N,N)

# -------------------------------
# Función para imponer condiciones periódicas
# -------------------------------
def imponer_condiciones_periodicas(x, y):
    x[:, 0] = x[:, N]
    y[:, 0] = y[:, N]
    x[:, N+1] = x[:, 1]
    y[:, N+1] = y[:, 1]

    x[0, :] = x[N, :]
    y[0, :] = y[N, :]
    x[N+1, :] = x[1, :]
    y[N+1, :] = y[1, :]

# Imponemos condiciones periódicas al inicio
imponer_condiciones_periodicas(x, y)

# -------------------------------
# Preparación de archivos
# -------------------------------
file_x = open("evolucion_x.txt", "w")
file_y = open("evolucion_y.txt", "w")

# -------------------------------
# Simulación temporal
# -------------------------------
dxdt = np.zeros((N+2, N+2))
dydt = np.zeros((N+2, N+2))
lap_x = np.zeros((N+2, N+2))
lap_y = np.zeros((N+2, N+2))

for step in range(steps):
    # Calcular laplacianos y derivadas
    for i in range(1, N+1):
        for j in range(1, N+1):
            lap_x[i, j] = (x[i+1, j] + x[i-1, j] + x[i, j+1] + x[i, j-1] - 4 * x[i, j]) / dx**2
            lap_y[i, j] = (y[i+1, j] + y[i-1, j] + y[i, j+1] + y[i, j-1] - 4 * y[i, j]) / dy**2

            dxdt[i, j] = a - (b + 1) * x[i, j] + x[i, j]**2 * y[i, j] + dX * lap_x[i, j]
            dydt[i, j] = b * x[i, j] - x[i, j]**2 * y[i, j] + dY * lap_y[i, j]

    # Actualizar variables
    x += dt * dxdt
    y += dt * dydt

    # Imponer condiciones periódicas
    imponer_condiciones_periodicas(x, y)

    # Guardar en archivo
    for i in range(1, N+1):
        fila_x = ", ".join(f"{x[i, j]:.6f}" for j in range(2, N+2))
        fila_y = ", ".join(f"{y[i, j]:.6f}" for j in range(2, N+2))

        file_x.write(fila_x + "\n")
        file_y.write(fila_y + "\n")

    # Separador entre bloques temporales
    file_x.write("\n")
    file_y.write("\n")

# -------------------------------
# Cerrar archivos
# -------------------------------
file_x.close()
file_y.close()

print("Evolución guardada en 'evolucion_x.txt' y 'evolucion_y.txt'")